steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/apac-cohort2-track3/koe-syndicate/ui-client:latest', '-f', 'Dockerfile.ui_client', '.']
images:
- 'us-central1-docker.pkg.dev/apac-cohort2-track3/koe-syndicate/ui-client:latest'
